### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by khanspers** [cytoscape/cyBrowser#3]
Downloading files from links in CyBrowser doesn't seem to work. First noticed this with txv files, but seems to be true also for other files. No error message or crash, but nothing happens and the filename just gets appended to the URL.

Try these:
https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/functional-enrichment/#/0/2 (tsv file)
https://cytoscape.github.io/cytoscape-tutorials/protocols/modules/basic-data-visualization/#/0/1 (session)

**Comment by scootermorris** [comment]
I think I have this fixed in the new release.  Note that it will really depend on how the web page does the download.  It turns out that there are many ways of doing it, unfortunately.
